name: Release

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: Pre-release
        required: true
        type: boolean
      options:
        description: Extra options
        type: string

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yaml

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: ci
    concurrency: release

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install -U pip poetry
        poetry config virtualenvs.in-project true
        poetry install --no-interaction
    - name: Semantic Release
      run: |
        pip install python-semantic-release
        git config user.name github-actions
        git config user.email github-actions@github.com
        semantic-release publish ${{ inputs.prerelease && '--prerelease' || '' }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPOSITORY_USERNAME: __token__
        REPOSITORY_PASSWORD: ${{ secrets.PYPI_TOKEN }}
